export enum NotificationType {
  OVERDUE_STEP = 'OVERDUE_STEP',
  OVERDUE_WORKFLOW = 'OVERDUE_WORKFLOW',
  WORKFLOW_APPROVED = 'WORKFLOW_APPROVED',
  WORKFLOW_REJECTED = 'WORKFLOW_REJECTED',
  WORKFLOW_RETURNED = 'WORKFLOW_RETURNED',
  WORKFLOW_RESUBMITTED = 'WORKFLOW_RESUBMITTED',
  NEW_APPROVAL_REQUEST = 'NEW_APPROVAL_REQUEST',
  SYSTEM = 'SYSTEM',
}
